import Head from 'next/head'
import StepsSection from '../src/components/steps/StepsSection'
import HeroSection from '../src/components/HeroSection'
import SloganGeneratorSection from '../src/components/slogan-generator/SloganGeneratorSection'
import styles from '../styles/Home.module.css'
import FreeProductsSection from '../src/components/products/FreeProductsSection'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Slogan Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroSection />
        <SloganGeneratorSection />
        <StepsSection />
        <FreeProductsSection />
      </main>

    </div>
  )
}
