import Head from 'next/head'
import StepsSection from '../src/components/steps/StepsSection'
import HeroSection from '../src/components/HeroSection'

import FreeProductsSection from '../src/components/products/FreeProductsSection'
import Footer from '../src/components/footer/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Slogan Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroSection />
        <StepsSection />
        <FreeProductsSection />
        <Footer />
      </main>

    </div>
  )
}
